package tasks

import (
	"time"

	"github.com/google/uuid"
)

// ─── Request DTOs ─────────────────────────────────────────────────────────────

// CreateTaskRequest carries the fields a manager/admin submits when creating
// a task (FR-TASK-01).
type CreateTaskRequest struct {
	OrgID       uuid.UUID  `json:"org_id"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Priority    Priority   `json:"priority"`
	DueDate     *time.Time `json:"due_date"`
}

// AssignedUserDTO carries display details of an assigned user
type AssignedUserDTO struct {
	ID       uuid.UUID `json:"id"`
	FullName string    `json:"full_name"`
	Email    string    `json:"email"`
	Role     string    `json:"role"`
}

// AssignableUserDTO carries details for member dropdown selector
type AssignableUserDTO struct {
	ID       uuid.UUID `json:"id"`
	OrgID    uuid.UUID `json:"org_id"`
	Email    string    `json:"email"`
	FullName string    `json:"full_name"`
	Role     string    `json:"role"`
	Status   string    `json:"status"`
}

// AssignTaskRequest carries the list of employee IDs, emails, or names to assign
// (FR-TASK-02).
type AssignTaskRequest struct {
	UserIDs     []uuid.UUID `json:"user_ids,omitempty"`
	Emails      []string    `json:"emails,omitempty"`
	Identifiers []string    `json:"identifiers,omitempty"`
}

// UnassignTaskRequest carries the single employee to remove from a task.
type UnassignTaskRequest struct {
	UserID     *uuid.UUID `json:"user_id,omitempty"`
	Identifier string     `json:"identifier,omitempty"`
}

// ChangeStatusRequest carries the desired new status (FR-TASK-04).
type ChangeStatusRequest struct {
	Status Status `json:"status"`
}

// ─── Timer request DTOs ───────────────────────────────────────────────────────

// TimerStartRequest carries the fields needed to open a timer segment
// (FR-TASK-05 / FR-TASK-10).
//
// RecordUUID is generated by the client before submission and acts as the
// idempotency key (FR-ATT-08 / FR-TASK-10): replaying the same payload with
// the same RecordUUID is a no-op.
//
// DeviceHash is the tamper-evident fingerprint of the submitting device.
// SyncStatus reflects whether this is being submitted online or replayed
// from an offline log.
type TimerStartRequest struct {
	TaskID     uuid.UUID  `json:"task_id"`
	StartedAt  time.Time  `json:"started_at"`
	DeviceHash string     `json:"device_hash"`
	RecordUUID uuid.UUID  `json:"record_uuid"`
	SyncStatus SyncStatus `json:"sync_status"`
}

// TimerPauseRequest closes the active segment and records the mandatory pause
// reason (FR-TASK-06).
type TimerPauseRequest struct {
	TaskID      uuid.UUID   `json:"task_id"`
	PausedAt    time.Time   `json:"paused_at"`
	PauseReason PauseReason `json:"pause_reason"`
	DeviceHash  string      `json:"device_hash"`
	RecordUUID  uuid.UUID   `json:"record_uuid"`
	SyncStatus  SyncStatus  `json:"sync_status"`
}

// TimerResumeRequest opens a new segment after a pause (FR-TASK-05).
type TimerResumeRequest struct {
	TaskID     uuid.UUID  `json:"task_id"`
	ResumedAt  time.Time  `json:"resumed_at"`
	DeviceHash string     `json:"device_hash"`
	RecordUUID uuid.UUID  `json:"record_uuid"`
	SyncStatus SyncStatus `json:"sync_status"`
}

// TimerStopRequest closes the active segment without a pause reason (FR-TASK-05).
type TimerStopRequest struct {
	TaskID     uuid.UUID  `json:"task_id"`
	StoppedAt  time.Time  `json:"stopped_at"`
	DeviceHash string     `json:"device_hash"`
	RecordUUID uuid.UUID  `json:"record_uuid"`
	SyncStatus SyncStatus `json:"sync_status"`
}

// ─── Response DTOs ────────────────────────────────────────────────────────────

// TaskResponse is the public representation of a task.
// AssignedTo carries the user IDs when available; AssignedUsers carries full user details.
type TaskResponse struct {
	ID            uuid.UUID         `json:"id"`
	OrgID         uuid.UUID         `json:"org_id"`
	Title         string            `json:"title"`
	Description   *string           `json:"description,omitempty"`
	Priority      Priority          `json:"priority"`
	Status        Status            `json:"status"`
	CreatedBy     uuid.UUID         `json:"created_by"`
	DueDate       *time.Time        `json:"due_date,omitempty"`
	CreatedAt     time.Time         `json:"created_at"`
	UpdatedAt     time.Time         `json:"updated_at"`
	AssignedTo    []uuid.UUID       `json:"assigned_to,omitempty"`
	AssignedUsers []AssignedUserDTO `json:"assigned_users,omitempty"`
}

// TimeLogResponse is the public shape of a single timer segment.
//
// PauseReason is omitted (nil) when the caller is not permitted to see it
// (FR-TASK-07).  The service layer performs the redaction; the response type
// carries the already-redacted value.
type TimeLogResponse struct {
	ID              uuid.UUID  `json:"id"`
	TaskID          uuid.UUID  `json:"task_id"`
	UserID          uuid.UUID  `json:"user_id"`
	StartedAt       time.Time  `json:"started_at"`
	StoppedAt       *time.Time `json:"stopped_at,omitempty"`
	DurationMinutes *int       `json:"duration_minutes,omitempty"`
	PauseReason     *string    `json:"pause_reason,omitempty"`
	SyncStatus      SyncStatus `json:"sync_status"`
	RecordUUID      uuid.UUID  `json:"record_uuid"`
	CreatedAt       time.Time  `json:"created_at"`
}

// TaskStatusCountsResponse wraps the aggregate counts by status (FR-TASK-09).
type TaskStatusCountsResponse struct {
	ToDo       int64 `json:"to_do"`
	InProgress int64 `json:"in_progress"`
	Paused     int64 `json:"paused"`
	Blocked    int64 `json:"blocked"`
	Completed  int64 `json:"completed"`
}

// ─── Conversion helpers ───────────────────────────────────────────────────────

// TaskToResponse converts a Task model to its response DTO.
// assignedTo and assignedUsers may be nil when not requested.
func TaskToResponse(t Task, assignedTo []uuid.UUID, assignedUsers []AssignedUserDTO) TaskResponse {
	return TaskResponse{
		ID:            t.ID.ID,
		OrgID:         t.OrgID,
		Title:         t.Title,
		Description:   t.Description,
		Priority:      t.Priority,
		Status:        t.Status,
		CreatedBy:     t.CreatedBy,
		DueDate:       t.DueDate,
		CreatedAt:     t.CreatedAt,
		UpdatedAt:     t.UpdatedAt,
		AssignedTo:    assignedTo,
		AssignedUsers: assignedUsers,
	}
}

// TimeLogToResponse converts a TaskTimeLog model to its response DTO.
// The service has already applied pause-reason redaction before this call.
func TimeLogToResponse(l TaskTimeLog) TimeLogResponse {
	return TimeLogResponse{
		ID:              l.ID.ID,
		TaskID:          l.TaskID,
		UserID:          l.UserID,
		StartedAt:       l.StartedAt,
		StoppedAt:       l.StoppedAt,
		DurationMinutes: l.DurationMinutes,
		PauseReason:     l.PauseReason,
		SyncStatus:      l.SyncStatus,
		RecordUUID:      l.RecordUUID,
		CreatedAt:       l.CreatedAt,
	}
}

// StatusCountsToResponse converts the map returned by the repository into a
// typed response struct.
func StatusCountsToResponse(m map[Status]int64) TaskStatusCountsResponse {
	return TaskStatusCountsResponse{
		ToDo:       m[StatusToDo],
		InProgress: m[StatusInProgress],
		Paused:     m[StatusPaused],
		Blocked:    m[StatusBlocked],
		Completed:  m[StatusCompleted],
	}
}
